/* Generated By:JavaCC: Do not edit this line. YakaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface YakaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BOOLEEN = 8;
  /** RegularExpression Id. */
  int VAR = 9;
  /** RegularExpression Id. */
  int FAIRE = 10;
  /** RegularExpression Id. */
  int SINON = 11;
  /** RegularExpression Id. */
  int POUR = 12;
  /** RegularExpression Id. */
  int SI = 13;
  /** RegularExpression Id. */
  int FSI = 14;
  /** RegularExpression Id. */
  int ENTIER = 15;
  /** RegularExpression Id. */
  int ERREUR = 16;
  /** RegularExpression Id. */
  int RETOURNE = 17;
  /** RegularExpression Id. */
  int VRAI = 18;
  /** RegularExpression Id. */
  int TANTQUE = 19;
  /** RegularExpression Id. */
  int CONST = 20;
  /** RegularExpression Id. */
  int FAUX = 21;
  /** RegularExpression Id. */
  int FAIT = 22;
  /** RegularExpression Id. */
  int OU = 23;
  /** RegularExpression Id. */
  int ET = 24;
  /** RegularExpression Id. */
  int NON = 25;
  /** RegularExpression Id. */
  int FONCTION = 26;
  /** RegularExpression Id. */
  int FFONCTION = 27;
  /** RegularExpression Id. */
  int PROGRAMME = 28;
  /** RegularExpression Id. */
  int FPROGRAMME = 29;
  /** RegularExpression Id. */
  int PRINCIPAL = 30;
  /** RegularExpression Id. */
  int FPRINCIPAL = 31;
  /** RegularExpression Id. */
  int ALORS = 32;
  /** RegularExpression Id. */
  int ECRIRE = 33;
  /** RegularExpression Id. */
  int LIRE = 34;
  /** RegularExpression Id. */
  int ALALIGNE = 35;
  /** RegularExpression Id. */
  int ADD = 36;
  /** RegularExpression Id. */
  int SUBNEG = 37;
  /** RegularExpression Id. */
  int OR = 38;
  /** RegularExpression Id. */
  int MUL = 39;
  /** RegularExpression Id. */
  int DIV = 40;
  /** RegularExpression Id. */
  int AND = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int EGAL = 43;
  /** RegularExpression Id. */
  int DIFF = 44;
  /** RegularExpression Id. */
  int INF = 45;
  /** RegularExpression Id. */
  int INFEGAL = 46;
  /** RegularExpression Id. */
  int SUP = 47;
  /** RegularExpression Id. */
  int SUPEGAL = 48;
  /** RegularExpression Id. */
  int chiffre = 49;
  /** RegularExpression Id. */
  int entier = 50;
  /** RegularExpression Id. */
  int lettre = 51;
  /** RegularExpression Id. */
  int ident = 52;
  /** RegularExpression Id. */
  int chaine = 53;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(*\"",
    "<token of kind 6>",
    "\"*)\"",
    "\"BOOLEEN\"",
    "\"VAR\"",
    "\"FAIRE\"",
    "\"SINON\"",
    "\"POUR\"",
    "\"SI\"",
    "\"FSI\"",
    "\"ENTIER\"",
    "\"ERREUR\"",
    "\"RETOURNE\"",
    "\"VRAI\"",
    "\"TANTQUE\"",
    "\"CONST\"",
    "\"FAUX\"",
    "\"FAIT\"",
    "\"OU\"",
    "\"ET\"",
    "\"NON\"",
    "\"FONCTION\"",
    "\"FFONCTION\"",
    "\"PROGRAMME\"",
    "\"FPROGRAMME\"",
    "\"PRINCIPAL\"",
    "\"FPRINCIPAL\"",
    "\"ALORS\"",
    "\"ECRIRE\"",
    "\"LIRE\"",
    "\"ALALIGNE\"",
    "\"+\"",
    "\"-\"",
    "\"OR\"",
    "\"*\"",
    "\"/\"",
    "\"AND\"",
    "\"NOT\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<chiffre>",
    "<entier>",
    "<lettre>",
    "<ident>",
    "<chaine>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
  };

}
